### ISSUE TITLE
Error when try install with composer

### ISSUE THREAD

**Issue by JacquesMarques** [AlexGx/yii2-phpexcel#3]
Hi,

When I try:

php composer.phar require "alexgx/yii2-phpexcel" "*"

I receive an error message:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package alexgx/yii2-phpexcel could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by amit5992** [comment]
Add following 

``` 
   "minimum-stability": "dev",
    "prefer-stable": true,
```

in ```composer.json```  than update composer

**Comment by Ir00man** [comment]
Or just write this to `composer.json`:
`"alexgx/yii2-phpexcel" : "dev-master"`
